<script lang="ts">
  import { api, type TenantId } from './lib/api';
  import type { Page } from './lib/pages';

  // Svelte 5 runes. `tenantId` is bindable because the header control rewrites it,
  // and the reactive values are `$state` rather than plain `let`.
  interface Props {
    tenantId: TenantId;
    port: number;
  }

  let { tenantId = $bindable(), port }: Props = $props();

  const pages: Page[] = [
    { slug: 'drafts', label: 'Product drafts', description: 'Draft definitions and their guardrail state.' },
    { slug: 'guardrails', label: 'Guardrails', description: 'Findings with severity and remediation.' },
    { slug: 'versions', label: 'Versions', description: 'Published versions and material differences.' },
  ];

  let banner = $state<string | null>(null);
  let current = $state<string>(readHash());

  // Hash routing is done here rather than through a router library: the app has
  // three sections and no nested routes, so a dependency would add types and
  // runtime behaviour for nothing a few lines cannot express.
  function readHash(): string {
    const raw = window.location.hash.replace(/^#/, '');
    return raw.length > 0 ? raw : '/';
  }

  $effect(() => {
    const onHashChange = (): void => {
      current = readHash();
    };
    window.addEventListener('hashchange', onHashChange);
    return () => window.removeEventListener('hashchange', onHashChange);
  });

  const active = $derived(current === '/' ? null : pages.find((p) => p.slug === current.slice(1)));

  let preview = $state('Loading...');

  // Fetched in an effect rather than awaited in the template: `await` in a
  // template expression needs an experimental compiler flag, and a section that
  // shows a loading state and then a result is better UX anyway.
  $effect(() => {
    const slug = active?.slug;
    if (!slug) {
      preview = '';
      return;
    }
    let cancelled = false;
    void api.preview(port, tenantId, slug).then((result: string) => {
      if (!cancelled) preview = result;
    });
    return () => {
      cancelled = true;
    };
  });

  function changeTenant(): void {
    const next = window.prompt('Tenant id', tenantId);
    if (next) {
      tenantId = next.trim();
      localStorage.setItem('pas.tenantId', tenantId);
      banner = `Now querying tenant ${tenantId}.`;
      setTimeout(() => (banner = null), 4000);
    }
  }
</script>

<main>
  <header style="--accent: #e8710a">
    <div class="identity">
      <h1>Product Config</h1>
      <p>Configure, validate and publish insurance products without code.</p>
    </div>
    <div class="controls">
      <span class="port">api :8004</span>
      <button onclick={changeTenant}>tenant: {tenantId}</button>
    </div>
  </header>

  {#if banner}
    <p class="banner" role="status">{banner}</p>
  {/if}

  <nav>
    {#each pages as page}
      <a href="#/{page.slug}" class:active={current === '/' + page.slug}>{page.label}</a>
    {/each}
  </nav>

  <section>
    {#if !active}
      <p class="hint">Choose a section.</p>
    {:else}
      <h2>{active.label}</h2>
      <p class="hint">{active.description}</p>
      <pre class="payload">{preview}</pre>
    {/if}
  </section>

  <footer>
    <p>
      Product Config administration UI. Generated by scripts/generate_ui.py &mdash; edit the
      generator, not this file.
    </p>
  </footer>
</main>

<style>
:global(body) {
    font-family: ui-sans-serif, system-ui, -apple-system, 'Segoe UI', sans-serif;
    color: #111827;
    background: #f9fafb;
    margin: 0;
  }
  main { max-width: 68rem; margin: 0 auto; padding: 1.5rem; }
  header {
    display: flex;
    justify-content: space-between;
    align-items: flex-start;
    gap: 1rem;
    border-left: 4px solid var(--accent);
    padding-left: 1rem;
  }
  h1 { font-size: 1.4rem; margin: 0; }
  .identity p { margin: 0.25rem 0 0; color: #4b5563; font-size: 0.9rem; }
  .controls { display: flex; align-items: center; gap: 0.5rem; }
  .port { font-family: ui-monospace, monospace; font-size: 0.8rem; color: #6b7280; }
  button {
    border: 1px solid #d1d5db;
    background: white;
    border-radius: 0.375rem;
    padding: 0.35rem 0.7rem;
    cursor: pointer;
    font-size: 0.8rem;
  }
  .banner {
    background: #ecfdf5;
    border: 1px solid #6ee7b7;
    border-radius: 0.375rem;
    padding: 0.5rem 0.75rem;
    font-size: 0.85rem;
  }
  nav { display: flex; gap: 0.5rem; margin: 1.25rem 0; flex-wrap: wrap; }
  nav a {
    text-decoration: none;
    color: #374151;
    border: 1px solid #e5e7eb;
    background: white;
    border-radius: 999px;
    padding: 0.3rem 0.85rem;
    font-size: 0.85rem;
  }
  nav a.active { background: var(--accent); color: white; border-color: var(--accent); }
  h2 { font-size: 1.05rem; margin: 0 0 0.25rem; }
  .hint { color: #6b7280; font-size: 0.85rem; margin: 0 0 0.75rem; }
  .payload {
    background: #111827;
    color: #e5e7eb;
    padding: 1rem;
    border-radius: 0.5rem;
    overflow: auto;
    font-size: 0.78rem;
    line-height: 1.5;
  }
  footer { margin-top: 2rem; color: #9ca3af; font-size: 0.75rem; }
</style>
